version: '3.1'
services:
  jupyter:
    build:
      context: docker
      dockerfile: Dockerfile-python
    environment:
      - "PASSWORD=datahack"
      - "JUPYTER_ENABLE_LAB=1"
    ports:
      - "8999:8999"
    volumes:
      - './home:/home/jovyan'
    command: ["start-notebook.sh", "--FileContentsManager.allow_hidden=True", "--port", "8999"]
  rstudio:
    build:
      context: docker
      dockerfile: Dockerfile-r
    environment:
      - "PASSWORD=datahack"
    volumes:
      - './home:/home/rstudio'
    ports:
      - "8787:8787"
