version: '3.1'
services:
  jupyter:
    build:
      context: docker
      dockerfile: Dockerfile-python
    environment:
      - "PASSWORD=datahack"
      - "DATAHACK_DB_PASS=${DATAHACK_DB_PASS}"
      - "DATAHACK_DB_USER=${DATAHACK_DB_USER}"
    ports:
      - "8999:8999"
    volumes:
      - './home:/home/jovyan'
    command: ["start-notebook.sh", "--port", "8999"]
  rstudio:
    build:
      context: docker
      dockerfile: Dockerfile-r
    environment:
      - "PASSWORD=datahack"
      - "DATAHACK_DB_PASS=${DATAHACK_DB_PASS}"
      - "DATAHACK_DB_USER=${DATAHACK_DB_USER}"
    volumes:
      - './home:/home/rstudio'
    ports:
      - "8787:8787"
